version: "3.9"
services:
  app:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    container_name: drive-app
  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
    container_name: drive-db

